# Generated by Django 4.0.1 on 2022-05-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('movieID', models.IntegerField(default=0)),
                ('streaming_service', models.CharField(max_length=30)),
                ('average_rating', models.IntegerField(default=0)),
                ('streaming_url', models.URLField()),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('genre', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_name', models.CharField(max_length=256)),
                ('serviceID', models.IntegerField(primary_key=True, serialize=False)),
                ('base_url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.ManyToManyField(to='marmot.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('favorites', models.ManyToManyField(to='marmot.Movies')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewer', models.CharField(max_length=256)),
                ('reviewID', models.IntegerField(primary_key=True, serialize=False)),
                ('movieID', models.ManyToManyField(to='marmot.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_name', models.CharField(max_length=50)),
                ('genreID', models.IntegerField(primary_key=True, serialize=False)),
                ('liked_categories', models.ManyToManyField(to='marmot.Movies')),
            ],
        ),
    ]
