# Generated by Django 4.0.1 on 2022-05-16 22:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marmot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='liked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='watched',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movieID',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='streaming_service',
            field=models.CharField(max_length=500),
        ),
    ]
