# Generated by Django 4.0.1 on 2022-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marmot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movieID',
            field=models.CharField(max_length=20),
        ),
    ]
