# Generated by Django 4.0.1 on 2022-05-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marmot', '0003_rename_first_name_user_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
    ]
